---
title: 基本的な書き方
jupyter: python3
---

### ダブルクォテーション3つで囲む

文字列全体を囲む際、3つ連続したクォーテーションで囲む ことで、エスケープシーケンスと同様、文字列内のクォーテーションをそのまま利用できます。\
クォーテーション3つで囲ったもの（''', """）は、本来は「改行を含む文字列を定義する」ための機能です。\
このような文字列は ヒアドキュメント（英: here document）と呼ばれます。

```{python}
print('''I'm Taro Tech''')
```

```{python}
print("""統計学
---
統計学(とうけいがく、英: statistics)とは、統計に関する研究を行う学問である。""")
```

## 関数とメソッド

### 関数

基本的には　関数名(引数)　という書き方をする。\
ただし、モジュールの中の関数は　モジュール名.関数名（引数）となる。\
\
モジュールを自作する場合、 モジュール名.py というファイルを作成し、その中で def() を使い関数を定義する。 \### メソッド メソッドはオブジェクトが持っているもの。　オブジェクト名.メソッド名(引数)　という書き方になる。\
\
メソッドを呼び出しただけでは中身のデータが上書きされないメソッドのことを 非破壊的メソッド という。\
一方、破壊的メソッドは変数への格納し直し等をしなくても変数そのものを書き換えるので要注意。

### 文字列型オブジェクトの代表的なメソッド（非破壊）

```{python}
a = "Today is a sunny day."
```

```{python}
# .replace()　置換
a.replace("sunny", "rainy")
```

```{python}
# .count()　文字カウント
a.count("a")
```

```{python}
# f-string 変数を埋め込む
station1 = "東京"
station2 = "熱海"
price = 2400
str1 = f"{station1}から{station2}までの運賃は{price:,}円です。" # ":,"はカンマ区切り表示の指定
str1
```

※書籍指定文字列の文法　https://docs.python.org/ja/3/library/string.html#format-string-syntax

### list型の代表的なメソッド (破壊的メソッド)

```{python}
# .append()　要素の末尾追加
fruits = []
fruits.append("apple")
fruits.append("banana")
fruits.append("orange")

fruits
```

```{python}
#. insert() 要素の途中追加
fruits.insert(1, "peach")

fruits
```

```{python}
# .pop()　リストの途中削除　※引数は削除する要素の位置。省略すると末尾を削除
fruits.pop()

fruits
```

## if文の制御構文

-   break：繰り返し処理から抜ける
-   continue：繰り返し処理の最初に戻る
-   pass：何もせずに先へ進む

## シーケンス

他の言語で「配列」とよく呼ばれるもの。Pythonでは以下のものがシーケンスとして用意されている。

-   リスト(list)
-   タプル(tuple)
-   レンジ(range)
-   文字列(string)

以下は順番を持たないのでシーケンスではないが、要素の集合として扱える。

-   セット(set)
-   辞書(dict)
